proyecto_final/LoVisto/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('format=xml', views.index_xml),
    path('format=json', views.index_json),
    path('<str:llave>/format=xml', views.get_content_xml),
    path('<str:llave>/format=json', views.get_content_json),
    path('logout', views.logout_view),
    path('<str:llave>', views.get_content, name='get_content')
]

proyecto_final/projecto_final/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('LoVisto/', include('LoVisto.urls')),


]

proyecto_final/LoVisto/models.py
from django.db import models

class Youtube(models.Model):
    title = models.CharField(max_length=128)
    author_name = models.CharField(max_length=128)
    author_url = models.CharField(max_length=128)
    video_embed = models.CharField(max_length=128)
    youtube_url = models.CharField(max_length=128)
    title_user = models.CharField(max_length=128)
    description = models.CharField(max_length=128)
    fecha = models.DateTimeField(auto_now=True)
    vote_negative = models.IntegerField(default=0)
    vote_positive = models.IntegerField(default=0)
    user_post = models.CharField(max_length=64)
    num_comentario = models.IntegerField(default=0)
    def __str__(self):
        return self.title_user + " = " + str(self.id)

class Vote_Youtube(models.Model):
    content = models.ForeignKey(Youtube, on_delete=models.CASCADE)
    vote_user = models.CharField(max_length=128)
    vote = models.CharField(max_length=64)


class Comentario(models.Model):
    contenido = models.ForeignKey(Youtube, on_delete=models.CASCADE)
    comentario = models.TextField(blank=False)
    fecha = models.DateTimeField(auto_now=True)
    user_comentario = models.CharField(max_length=128)


class Aemet_Cover(models.Model):
    title_user = models.CharField(max_length=128)
    description = models.CharField(max_length=128)
    fecha = models.DateTimeField(auto_now=True)
    vote_negative = models.IntegerField(default=0)
    vote_positive = models.IntegerField(default=0)
    copyright = models.CharField(max_length=128)
    city = models.CharField(max_length=128)
    province = models.CharField(max_length=128)
    url_page = models.CharField(max_length=128)
    user_post = models.CharField(max_length=64)
    num_comentario = models.IntegerField(default=0)
    def __str__(self):
        return self.title_user + " = " + str(self.id)

class Aemet(models.Model):
    contenido = models.ForeignKey(Aemet_Cover, on_delete=models.CASCADE)
    day = models.CharField(max_length=64)
    temp_max = models.CharField(max_length=64)
    temp_min = models.CharField(max_length=64)
    sens_max = models.CharField(max_length=64)
    sens_min = models.CharField(max_length=64)
    hum_max = models.CharField(max_length=64)
    hum_min = models.CharField(max_length=64)


class ComentarioAemet(models.Model):
    contenido = models.ForeignKey(Aemet_Cover, on_delete=models.CASCADE)
    comentario = models.TextField(blank=False)
    fecha = models.DateTimeField(auto_now=True)
    user_comentario = models.CharField(max_length=128)

class Vote_Aemet(models.Model):
    content = models.ForeignKey(Aemet_Cover, on_delete=models.CASCADE)
    vote_user = models.CharField(max_length=128)
    vote = models.CharField(max_length=64)

class Wikipedia(models.Model):
    title_user = models.CharField(max_length=128)
    description = models.CharField(max_length=128)
    fecha = models.DateTimeField(auto_now=True)
    articulo = models.CharField(max_length=128)
    articulo_text = models.CharField(max_length=400)
    articulo_photo = models.CharField(max_length=128)
    url_page = models.CharField(max_length=128)
    vote_negative = models.IntegerField(default=0)
    vote_positive = models.IntegerField(default=0)
    user_post = models.CharField(max_length=64)
    num_comentario = models.IntegerField(default=0)

    def __str__(self):
        return self.title_user + " = " + str(self.id)

class ComentarioWikipedia(models.Model):
    contenido = models.ForeignKey(Wikipedia, on_delete=models.CASCADE)
    comentario = models.TextField(blank=False)
    fecha = models.DateTimeField(auto_now=True)
    user_comentario = models.CharField(max_length=128)

class Vote_Wikipedia(models.Model):
    content = models.ForeignKey(Wikipedia, on_delete=models.CASCADE)
    vote_user = models.CharField(max_length=128)
    vote = models.CharField(max_length=64)


class All_Content(models.Model):
    title_user = models.CharField(max_length=128)
    description = models.CharField(max_length=128)
    fecha = models.DateTimeField(auto_now=True)
    vote_negative = models.IntegerField(default=0)
    vote_positive = models.IntegerField(default=0)
    num_comentario = models.IntegerField(default=0)
    url = models.CharField(max_length=128)
    user_post = models.CharField(max_length=64)

class Mode_User(models.Model):
    user = models.CharField(max_length=128)
    mode = models.CharField(max_length=128)

proyecto_final/LoVisto/views.py
from audioop import reverse

from django.shortcuts import get_object_or_404, render

from .aemetparser import AemetChannel
from .wikipediaparser import  WikipediaChannel

from .models import Youtube, Comentario, Vote_Youtube, Aemet, ComentarioAemet, Vote_Aemet, Aemet_Cover
from .models import ComentarioWikipedia, Vote_Wikipedia, Wikipedia, All_Content, Mode_User
from django.http import HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from django.template import loader
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import authenticate, login

import json
import urllib.request

@csrf_exempt
def index(request):
    msg = "hola"

    if request.method == "POST":
        # Coger el valor que haya en el cuerpo de HTTP
        action = request.POST["action"]

        if action == "Create user":
            username = request.POST["username"]
            password = request.POST["password"]
            email = request.POST["email"]

            if User.DoesNotExist:
                if username and password and email:
                    user = User.objects.create_user(username, email, password)
                    user.save()
            else:
                msg = "El usario ya está registrado"

        elif action == "login":
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
            else:
                msg = "Usuario o Contraseña erróneas"

        elif action == "Enviar":
            url = request.POST["URL"]
            if url.find('https://www.youtube.com') >= 0:
                description = request.POST["Description"]
                title_user = request.POST["title_user"]
                id_video = url.split('=')[-1]
                url_jason ="https://www.youtube.com/oembed?format=json&url=https://www.youtube.com/watch?v=" + str(id_video)


                video_embed = "https://www.youtube.com/embed/" + str(id_video)


                with urllib.request.urlopen(url_jason) as json_doc:
                    json_str = json_doc.read().decode(encoding="ISO-8859-1")
                    munis = json.loads(json_str)
                    c = Youtube(title=munis['title'], author_name=munis['author_name'], author_url=munis['author_url'],
                                video_embed=video_embed, youtube_url=url, description=description, title_user=title_user,
                                user_post=request.user.username)
                    c.save()

                    d = All_Content(title_user=title_user, description=description, url=url, user_post=request.user.username)
                    d.save()

            elif url.find('http://www.aemet.es') >= 0:
                description = request.POST["Description"]
                title_user = request.POST["title_user"]
                corte = url.split('/')[-1]
                num = corte.split('-id')[1]
                city = corte.split('-id')[0]
                msg = num + city
                url_xml = "https://www.aemet.es/xml/municipios/localidad_" + num + ".xml"
                xmlStream = urllib.request.urlopen(url_xml)
                aemet = AemetChannel(xmlStream)
                datos_aemet = aemet.prediccion()

                d = Aemet_Cover(copyright=datos_aemet[1]['copyright'], title_user=title_user, description=description,
                                city=city, province=datos_aemet[1]['province'], url_page=url,user_post=request.user.username)
                d.save()
                contenido = get_object_or_404(Aemet_Cover, title_user=title_user)
                for datos in datos_aemet:
                    c = Aemet(contenido=contenido, day=datos['day'], temp_max=datos['temp_max'], temp_min=datos['temp_min'],
                            sens_max=datos['sens_max'], sens_min=datos['sens_min'], hum_max=datos['hum_max'],
                            hum_min=datos['hum_min'])
                    c.save()

                d = All_Content(title_user=title_user, description=description, url=url,
                                user_post=request.user.username)
                d.save()
            elif url.find('https://es.wikipedia.org') >= 0:
                description = request.POST["Description"]
                title_user = request.POST["title_user"]
                articulo = url.split('/')[-1]
                url_articulo = 'https://es.wikipedia.org/w/api.php?action=query&format=xml&titles='+ \
                               articulo + '&prop=extracts&exintro&explaintext'

                xmlStream = urllib.request.urlopen(url_articulo)
                wikipedia_articulo = WikipediaChannel(xmlStream)
                articulo_text = wikipedia_articulo.articulo()

                url_foto = 'https://es.wikipedia.org/w/api.php?action=query&titles='+ \
                           articulo + '&prop=pageimages&format=json&pithumbsize=100'

                with urllib.request.urlopen(url_foto) as json_doc:
                    json_str = json_doc.read().decode(encoding="ISO-8859-1")
                    munis = json.dumps(json.loads(json_str))
                    try:
                        articulo_photo = munis.split('"source"')[1].split('"width"')[0][3:][:-3]
                    except:
                        articulo_photo = ""
                    c = Wikipedia(title_user=title_user, description=description, articulo=articulo,
                                  articulo_text=articulo_text, url_page=url, articulo_photo=articulo_photo,
                                  user_post=request.user.username)
                    c.save()
                    d = All_Content(title_user=title_user, description=description, url=url,
                                    user_post=request.user.username)
                    d.save()


        elif action == "Me gusta":
            llave = request.POST["name_post"]
            try:
                youtube = Youtube.objects.get(title_user=llave)

                try:
                    content_vote = Vote_Youtube.objects.get(vote_user=request.user.username, content=youtube)
                    if content_vote.vote == "Negative":
                        content_vote.vote = "Positive"
                        content_vote.save()
                        youtube.vote_positive = youtube.vote_positive + 1
                        youtube.vote_negative = youtube.vote_negative - 1

                        all_content = All_Content.objects.get(title_user=llave)
                        all_content.vote_negative = youtube.vote_negative
                        all_content.vote_positive = youtube.vote_positive

                        youtube.save()
                        all_content.save()
                except Vote_Youtube.DoesNotExist:
                    q = Vote_Youtube(content=youtube, vote_user=request.user.username, vote="Positive")
                    q.save()
                    youtube.vote_positive = youtube.vote_positive + 1
                    all_content = All_Content.objects.get(title_user=llave)
                    all_content.vote_positive = youtube.vote_positive

                    youtube.save()
                    all_content.save()


            except Youtube.DoesNotExist:
                s = 0
            # No hacemos nada
            try:

                aemet = Aemet_Cover.objects.get(title_user=llave)

                try:
                    content_vote = Vote_Aemet.objects.get(vote_user=request.user.username, content=aemet)
                    if content_vote.vote == "Negative":
                        content_vote.vote = "Positive"
                        content_vote.save()
                        aemet.vote_positive = aemet.vote_positive + 1
                        aemet.vote_negative = aemet.vote_negative - 1

                        all_content = All_Content.objects.get(title_user=llave)
                        all_content.vote_negative = aemet.vote_negative
                        all_content.vote_positive = aemet.vote_positive

                        all_content.save()
                        aemet.save()
                except Vote_Aemet.DoesNotExist:
                    q = Vote_Aemet(content=aemet, vote_user=request.user.username, vote="Positive")
                    q.save()
                    aemet.vote_positive = aemet.vote_positive + 1
                    all_content = All_Content.objects.get(title_user=llave)
                    all_content.vote_positive = aemet.vote_positive

                    aemet.save()
                    all_content.save()
            except Aemet_Cover.DoesNotExist:
                s = 0
            # No hacemos nada
            try:

                wikipedia = Wikipedia.objects.get(title_user=llave)
                try:
                    content_vote = Vote_Wikipedia.objects.get(vote_user=request.user.username, content=wikipedia)
                    if content_vote.vote == "Negative":
                        content_vote.vote = "Positive"
                        content_vote.save()
                        wikipedia.vote_positive = wikipedia.vote_positive + 1
                        wikipedia.vote_negative = wikipedia.vote_negative - 1

                        all_content = All_Content.objects.get(title_user=llave)
                        all_content.vote_negative = wikipedia.vote_negative
                        all_content.vote_positive = wikipedia.vote_positive

                        wikipedia.save()
                        all_content.save()
                except Vote_Wikipedia.DoesNotExist:
                    q = Vote_Wikipedia(content=wikipedia, vote_user=request.user.username, vote="Positive")
                    q.save()

proyecto_final/templates/LoVisto/content_aemet.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" >
      {% if user_authenticated %}
        {% if mode == 'Dark' %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/dark.css' %}" >
        {% endif %}
      {% endif %}
  </head>

  <body class="text-center">
    {% if user_authenticated %}
    <form action="" method="POST">
        {% csrf_token %}
        Cambiar modo: <input type="submit"  class="btn btn-light" name="action" value="Light">
        <input type="submit" class="btn btn-dark" name="action" value="Dark">
        <input type="hidden" name="user" value="{{user_on}}">
    </form>
    {% endif %}
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="/LoVisto">Home</a>
            <a class="nav-link active" href="/LoVisto/{{ content.title_user }}/format=xml">formato xml</a>
            <a class="nav-link active" href="/LoVisto/{{ content.title_user }}/format=json">formato json</a>
            <a class="nav-link" href="/LoVisto/logout">Cerrar sesión</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">

        <img src="{% static 'LoVisto/logo-aemet.png' %}" class="center-block" height="250">
        <h1 class="cover-heading">{{ content.title_user }}.</h1>
        <p class="lead">Descripción: {{ content.description }}

        <div class="aemet">
          <p>Datos AEMET para {{ content.city }} ({{ content.province }})</p>
          {% for tiempo in content.aemet_set.all %}
            <ul><li>{{tiempo.day }}. Temperatura: {{ tiempo.temp_min }} /{{ tiempo.temp_max }},
                    sensación: {{ tiempo.sens_min }}/ {{ tiempo.sens_max}}, humedad: {{ tiempo.hum_min }}/{{ tiempo.hum_max }}.</li>
            </ul>
          {% endfor %}
          <p>Copyright AEMET: {{ content.copyright }}.
            <a href={{content.url_page}}>Página original en AEMET</a></p>

        </div>
        {% if user_authenticated %}
        <form action="" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-primary active" name="action" value="Me gusta">
          <input type="submit" class="btn btn-primary active" name="action" value="No me gusta">
        </form>
        <br><h6>Likes: <span class="badge bg-secondary">{{ content.vote_positive }}</span> </h6>
        <h6>Dislikes: <span class="badge bg-secondary">{{ content.vote_negative }}</span> </h6>

          <br><br>
          <h3> Añade un comentario </h3>
            <form action=""  method= "POST" >
                {% csrf_token %}
                <table>
                    <tr>
                      Comentario: <input type="text" name="Commentary" value="" placeholder="">
                    </tr>
                    <tr>
                      <input type="submit" name="action" value="Enviar Comentario">
                    </tr>
                </table>
            </form>
        {% endif %}
        <br><br>
        {% if content.comentarioaemet_set.all %}
          <h3> Comentarios: </h3>
          {% for comentario in content.comentarioaemet_set.all %}
          <hr>
          <h4>Comentario realizado por {{ comentario.user_comentario }} </h4><br>
              {{ comentario.comentario }}<br>
              Enviado el {{ comentario.fecha }}<br>
          {% endfor %}
        {% endif %}

        <img src="{% static 'LoVisto/Logo_URJC.png' %}" class="center-block">
      </main>

    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>

</html>

proyecto_final/templates/LoVisto/content_wikipedia.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" >
      {% if user_authenticated %}
        {% if mode == 'Dark' %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/dark.css' %}" >
        {% endif %}
      {% endif %}
  </head>

  <body class="text-center">
    {% if user_authenticated %}
    <form action="" method="POST">
        {% csrf_token %}
        Cambiar modo: <input type="submit"  class="btn btn-light" name="action" value="Light">
        <input type="submit" class="btn btn-dark" name="action" value="Dark">
        <input type="hidden" name="user" value="{{user_on}}">
    </form>
    {% endif %}
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="/LoVisto">Home</a>
            <a class="nav-link active" href="/LoVisto/{{ content.title_user }}/format=xml">formato xml</a>
            <a class="nav-link active" href="/LoVisto/{{ content.title_user }}/format=json">formato json</a>
            <a class="nav-link" href="/LoVisto/logout">Cerrar sesión</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <img src="{% static 'LoVisto/wikipedia.png' %}" class="center-block" height="250">
        <h1 class="cover-heading">{{ content.title_user }}.</h1>
        <p class="lead">Descripción: {{ content.description }}


        <div class="wikipedia">
          <p>Artículo Wikipedia: {{ content.articulo }} </p>
          <img src={{content.articulo_photo}}><p>
          {{ content.articulo_text}}</p>
          <p>Copyright Wikipedia.
              <a href={{content.url_page}}>Artículo original</a>.</p>
        </div>
        {% if user_authenticated %}
        <form action="" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-primary active" name="action" value="Me gusta">
          <input type="submit" class="btn btn-primary active" name="action" value="No me gusta">
        </form>
        <br><h6>Likes: <span class="badge bg-secondary">{{ content.vote_positive }}</span> </h6>
        <h6>Dislikes: <span class="badge bg-secondary">{{ content.vote_negative }}</span> </h6>

          <br><br>
          <h3> Añade un comentario </h3>
            <form action=""  method= "POST" >
                {% csrf_token %}
                <table>
                    <tr>
                      Comentario: <input type="text" name="Commentary" value="" placeholder="">
                    </tr>
                    <tr>
                      <input type="submit" name="action" value="Enviar Comentario">
                    </tr>
                </table>
            </form>
        {% endif %}
        <br><br>
        {% if content.comentariowikipedia_set.all %}
          <h3> Comentarios: </h3>
          {% for comentario in content.comentariowikipedia_set.all %}
          <hr>
          <h4>Comentario realizado por {{ comentario.user_comentario }} </h4><br>
              {{ comentario.comentario }}<br>
              Enviado el {{ comentario.fecha }}<br>
          {% endfor %}
        {% endif %}

        <img src="{% static 'LoVisto/Logo_URJC.png' %}" class="center-block">
      </main>

    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>

</html>

proyecto_final/templates/LoVisto/content_youtube.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" >
      {% if user_authenticated %}
        {% if mode == 'Dark' %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/dark.css' %}" >
        {% endif %}
      {% endif %}
  </head>

  <body class="text-center">
    {% if user_authenticated %}
    <form action="" method="POST">
        {% csrf_token %}
        Cambiar modo: <input type="submit"  class="btn btn-light" name="action" value="Light">
        <input type="submit" class="btn btn-dark" name="action" value="Dark">
        <input type="hidden" name="user" value="{{user_on}}">
    </form>
    {% endif %}
    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="/LoVisto">Home</a>
            <a class="nav-link active" href="/LoVisto/{{ content.title_user }}/format=xml">formato xml</a>
            <a class="nav-link active" href="/LoVisto/{{ content.title_user }}/format=json">formato json</a>
            {% if user_authenticated %}
            <a class="nav-link" href="/LoVisto/logout">Cerrar sesión</a>
            {% else %}
            <a class="nav-link" href="/LoVisto">Iniciar sesión</a>
            {% endif %}
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <img src="{% static 'LoVisto/YouTube-Logo.png' %}" class="center-block" height="250">
        <h1 class="cover-heading">{{ content.title_user }}.</h1>
        <p class="lead">Titulo youtube: {{ content.title }}
        <p class="lead">Descripción: {{ content.description }}


        <div class="youtube">
          <iframe width="560" height="315"
                  src={{content.video_embed}}
                  frameborder="0"
                  allow="accelerometer; encrypted-media; gyroscope; picture-in-picture"
                  allowfullscreen>
          </iframe>

          <p>Autor:{{ content.author_name }}. <a href={{content.youtube_url}}>Video en YouTube</a></p>
        </div>
        {% if user_authenticated %}
        <form action="" method="POST">
          {% csrf_token %}

          <input type="submit" class="btn btn-primary active" name="action" value="Me gusta">
          <input type="submit" class="btn btn-primary active" name="action" value="No me gusta">
        </form>
        <br><h6>Likes: <span class="badge bg-secondary">{{ content.vote_positive }}</span> </h6>
        <h6>Dislikes: <span class="badge bg-secondary">{{ content.vote_negative }}</span> </h6>

          <br><br>
          <h3> Añade un comentario </h3>
            <form action=""  method= "POST" >
                {% csrf_token %}
                <table>
                    <tr>
                      Comentario: <input type="text" name="Commentary" value="" placeholder="">
                    </tr>
                    <tr>
                      <input type="submit" name="action" value="Enviar Comentario">
                    </tr>
                </table>
            </form>
        {% endif %}
        <br><br>
        {% if content.comentario_set.all %}
          <h3> Comentarios: </h3>
          {% for comentario in content.comentario_set.all %}
          <hr>
          <h4>Comentario realizado por {{ comentario.user_comentario }} </h4><br>
              {{ comentario.comentario }}<br>
             Enviado el {{ comentario.fecha }}<br>
          {% endfor %}
        {% endif %}

        <img src="{% static 'LoVisto/Logo_URJC.png' %}" class="center-block">
      </main>

    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>

</html>

proyecto_final/templates/LoVisto/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error!</title>
</head>
<body>
    <h1>ERROR!</h1>
    <h3>No existe este contenido: {{ llave }}</h3>
    <p> Puedes añadirlo <a href="/LoVisto">aquí</a></p>
</body>
</html>